from __future__ import annotations

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from core.schema import Investigation

_AI_COLOR = RGBColor(0x4F, 0x46, 0xE5)
_WARN_COLOR = RGBColor(0x92, 0x40, 0x0E)


def _heading(doc: Document, text: str, level: int = 1):
    doc.add_heading(text, level=level)


def _table(doc: Document, headers: list[str], rows: list[list]):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    for i, h in enumerate(headers):
        table.rows[0].cells[i].text = h
    for row in rows:
        cells = table.add_row().cells
        for i, val in enumerate(row):
            cells[i].text = str(val)


def generate_docx(investigation: Investigation, output_path: str) -> str:
    inv = investigation
    doc = Document()

    title = doc.add_heading("OSINT-X AI Investigation Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    meta.add_run(f"Investigation ID: {inv.id}\n").bold = True
    meta.add_run(f"Target: {inv.target_type} = {inv.target_value}\n")
    meta.add_run(f"Started: {inv.started_at}\n")
    meta.add_run(f"Completed: {inv.completed_at or 'in progress'}")

    _heading(doc, "Executive Summary (AI-generated)")
    p = doc.add_paragraph(inv.ai_summary or "AI analysis unavailable for this run.")
    p.runs[0].font.color.rgb = _AI_COLOR if inv.ai_summary else RGBColor(0x66, 0x66, 0x66)

    _heading(doc, "Technical Summary (AI-generated)")
    doc.add_paragraph(inv.ai_technical_summary or "AI analysis unavailable for this run.")

    _heading(doc, "Risk Assessment (rule-based)")
    _table(doc, ["Metric", "Score"], [
        ["Confidence Score", inv.risk.confidence_score],
        ["Exposure Score", inv.risk.exposure_score],
        ["Investigation Completeness", inv.risk.investigation_completeness],
        ["Repository Exposure", inv.risk.repository_exposure],
        ["Technology Exposure", inv.risk.technology_exposure],
        ["Public Presence Score", inv.risk.public_presence_score],
    ])

    _heading(doc, "Collected Entities (raw facts)")
    _table(doc, ["Type", "Value", "Source", "Confidence"],
           [[e.type.value, e.value, e.source, e.confidence] for e in inv.entities])

    _heading(doc, "Tool Execution Results")
    _table(doc, ["Tool", "Status", "Entities Found", "Duration (s)"], [
        [tr.tool, "success" if tr.success else f"failed: {tr.error}", len(tr.entities), tr.duration_seconds]
        for tr in inv.tool_results
    ])

    if inv.timeline:
        _heading(doc, "Timeline")
        for ev in inv.timeline:
            doc.add_paragraph(f"{ev.timestamp} — {ev.description} (source: {ev.source})", style="List Bullet")

    _heading(doc, "AI Recommendations (AI-generated)")
    if inv.ai_recommendations:
        for rec in inv.ai_recommendations:
            doc.add_paragraph(rec, style="List Bullet")
    else:
        doc.add_paragraph("No AI recommendations available for this run.")

    if inv.warnings:
        _heading(doc, "Warnings / Limitations")
        for warning in inv.warnings:
            wp = doc.add_paragraph(f"⚠ {warning}", style="List Bullet")
            wp.runs[0].font.color.rgb = _WARN_COLOR

    doc.add_paragraph()
    footer = doc.add_paragraph(
        "Report generated by OSINT-X AI — collects only publicly available information from "
        "authorized/lawful sources. AI-generated sections are clearly marked and must be "
        "reviewed by a human analyst before action is taken."
    )
    footer.runs[0].italic = True

    doc.save(output_path)
    return output_path
