from __future__ import annotations

import html

from core.schema import Investigation

_CSS = """
body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; max-width: 960px; margin: 2rem auto; padding: 0 1rem; color: #1a1a2e; background: #f7f8fc; }
h1, h2 { color: #16213e; }
.badge { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 0.8em; font-weight: 600; }
.ai-section { background: #eef2ff; border-left: 4px solid #4f46e5; padding: 1rem; border-radius: 6px; }
.fact-section { background: #fff; border: 1px solid #e2e8f0; padding: 1rem; border-radius: 6px; }
table { border-collapse: collapse; width: 100%; margin: 0.5rem 0 1.5rem; }
th, td { border: 1px solid #e2e8f0; padding: 6px 10px; font-size: 0.9em; text-align: left; }
th { background: #f1f5f9; }
.warning { color: #92400e; background: #fef3c7; padding: 8px 12px; border-radius: 6px; margin: 4px 0; }
footer { color: #64748b; font-size: 0.8em; margin-top: 2rem; }
"""


def _esc(value) -> str:
    return html.escape(str(value))


def generate_html(investigation: Investigation) -> str:
    inv = investigation
    entity_rows = "".join(
        f"<tr><td>{_esc(e.type.value)}</td><td>{_esc(e.value)}</td>"
        f"<td>{_esc(e.source)}</td><td>{_esc(e.confidence)}</td></tr>"
        for e in inv.entities
    )
    tool_rows = "".join(
        f"<tr><td>{_esc(tr.tool)}</td>"
        f"<td>{'✅ success' if tr.success else '❌ ' + _esc(tr.error or 'failed')}</td>"
        f"<td>{len(tr.entities)}</td><td>{tr.duration_seconds}</td></tr>"
        for tr in inv.tool_results
    )
    timeline_items = "".join(
        f"<li><strong>{_esc(ev.timestamp)}</strong> — {_esc(ev.description)} "
        f"<em>(source: {_esc(ev.source)})</em></li>"
        for ev in inv.timeline
    )
    recs = "".join(f"<li>{_esc(r)}</li>" for r in inv.ai_recommendations) or "<li><em>None available.</em></li>"
    warnings = "".join(f"<div class='warning'>⚠️ {_esc(w)}</div>" for w in inv.warnings)
    risk_rows = "".join(
        f"<tr><td>{_esc(k)}</td><td>{_esc(v)}</td></tr>"
        for k, v in [
            ("Confidence Score", inv.risk.confidence_score),
            ("Exposure Score", inv.risk.exposure_score),
            ("Investigation Completeness", inv.risk.investigation_completeness),
            ("Repository Exposure", inv.risk.repository_exposure),
            ("Technology Exposure", inv.risk.technology_exposure),
            ("Public Presence Score", inv.risk.public_presence_score),
        ]
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>OSINT-X AI Report — {_esc(inv.target_value)}</title>
<style>{_CSS}</style>
</head>
<body>
<h1>OSINT-X AI Investigation Report</h1>
<p><strong>ID:</strong> {_esc(inv.id)} &nbsp;|&nbsp; <strong>Target:</strong> {_esc(inv.target_type)} = {_esc(inv.target_value)}<br>
<strong>Started:</strong> {_esc(inv.started_at)} &nbsp;|&nbsp; <strong>Completed:</strong> {_esc(inv.completed_at or 'in progress')}</p>

<h2>Executive Summary <span class="badge">AI-generated</span></h2>
<div class="ai-section">{_esc(inv.ai_summary) if inv.ai_summary else '<em>AI analysis unavailable — see warnings.</em>'}</div>

<h2>Technical Summary <span class="badge">AI-generated</span></h2>
<div class="ai-section">{_esc(inv.ai_technical_summary) if inv.ai_technical_summary else '<em>AI analysis unavailable.</em>'}</div>

<h2>Risk Assessment <span class="badge">rule-based</span></h2>
<table><tr><th>Metric</th><th>Score</th></tr>{risk_rows}</table>

<h2>Collected Entities <span class="badge">raw facts</span></h2>
<table><tr><th>Type</th><th>Value</th><th>Source</th><th>Confidence</th></tr>{entity_rows}</table>

<h2>Tool Execution Results</h2>
<table><tr><th>Tool</th><th>Status</th><th>Entities</th><th>Duration (s)</th></tr>{tool_rows}</table>

<h2>Timeline</h2>
<ul>{timeline_items}</ul>

<h2>AI Recommendations <span class="badge">AI-generated</span></h2>
<ul>{recs}</ul>

<h2>Warnings / Limitations</h2>
{warnings}

<footer>Report generated by OSINT-X AI — collects only publicly available information from
authorized/lawful sources. AI-generated sections are clearly marked and must be reviewed by a
human analyst before action is taken.</footer>
</body>
</html>
"""
