from __future__ import annotations

from core.schema import Investigation


def generate_markdown(investigation: Investigation) -> str:
    inv = investigation
    lines = [
        f"# OSINT-X AI Investigation Report",
        "",
        f"**Investigation ID:** `{inv.id}`  ",
        f"**Target:** `{inv.target_type}` = `{inv.target_value}`  ",
        f"**Started:** {inv.started_at}  ",
        f"**Completed:** {inv.completed_at or 'in progress'}  ",
        "",
        "---",
        "",
        "## Executive Summary *(AI-generated)*",
        "",
        inv.ai_summary or "_AI analysis unavailable for this run — see warnings below._",
        "",
        "## Technical Summary *(AI-generated)*",
        "",
        inv.ai_technical_summary or "_AI analysis unavailable for this run._",
        "",
        "## Risk Assessment *(rule-based, not AI-generated)*",
        "",
        "| Metric | Score |",
        "|---|---|",
        f"| Confidence Score | {inv.risk.confidence_score} |",
        f"| Exposure Score | {inv.risk.exposure_score} |",
        f"| Investigation Completeness | {inv.risk.investigation_completeness} |",
        f"| Repository Exposure | {inv.risk.repository_exposure} |",
        f"| Technology Exposure | {inv.risk.technology_exposure} |",
        f"| Public Presence Score | {inv.risk.public_presence_score} |",
        "",
    ]

    if inv.risk.notes:
        lines.append("**Notes:**")
        for note in inv.risk.notes:
            lines.append(f"- {note}")
        lines.append("")

    lines += ["## Collected Entities *(raw facts, not AI-generated)*", ""]
    lines += ["| Type | Value | Source | Confidence |", "|---|---|---|---|"]
    for e in inv.entities:
        value = e.value.replace("|", "\\|")
        lines.append(f"| {e.type.value} | {value} | {e.source} | {e.confidence} |")
    lines.append("")

    lines += ["## Tool Execution Results", "", "| Tool | Status | Entities Found | Duration (s) |", "|---|---|---|---|"]
    for tr in inv.tool_results:
        status = "✅ success" if tr.success else f"❌ {tr.error or 'failed'}"
        lines.append(f"| {tr.tool} | {status} | {len(tr.entities)} | {tr.duration_seconds} |")
    lines.append("")

    if inv.timeline:
        lines += ["## Timeline", ""]
        for ev in inv.timeline:
            lines.append(f"- **{ev.timestamp}** — {ev.description} _(source: {ev.source})_")
        lines.append("")

    lines += ["## AI Recommendations *(AI-generated, lawful follow-up steps only)*", ""]
    if inv.ai_recommendations:
        for rec in inv.ai_recommendations:
            lines.append(f"- {rec}")
    else:
        lines.append("_No AI recommendations available for this run._")
    lines.append("")

    if inv.warnings:
        lines += ["## Warnings / Limitations", ""]
        for warning in inv.warnings:
            lines.append(f"- ⚠️ {warning}")
        lines.append("")

    lines += ["---", "", "_Report generated by OSINT-X AI — collects only publicly available information "
              "from authorized/lawful sources. AI-generated sections are clearly marked and must be "
              "reviewed by a human analyst before action is taken._"]

    return "\n".join(lines)
