from __future__ import annotations

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

from core.schema import Investigation


def generate_pdf(investigation: Investigation, output_path: str) -> str:
    inv = investigation
    doc = SimpleDocTemplate(output_path, pagesize=LETTER,
                             topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    ai_style = ParagraphStyle("AIText", parent=styles["BodyText"], textColor=colors.HexColor("#4F46E5"))
    warn_style = ParagraphStyle("WarnText", parent=styles["BodyText"], textColor=colors.HexColor("#92400E"))

    story = [
        Paragraph("OSINT-X AI Investigation Report", styles["Title"]),
        Spacer(1, 12),
        Paragraph(f"<b>Investigation ID:</b> {inv.id}", styles["BodyText"]),
        Paragraph(f"<b>Target:</b> {inv.target_type} = {inv.target_value}", styles["BodyText"]),
        Paragraph(f"<b>Started:</b> {inv.started_at}", styles["BodyText"]),
        Paragraph(f"<b>Completed:</b> {inv.completed_at or 'in progress'}", styles["BodyText"]),
        Spacer(1, 16),
        Paragraph("Executive Summary (AI-generated)", styles["Heading2"]),
        Paragraph(inv.ai_summary or "AI analysis unavailable for this run.", ai_style),
        Spacer(1, 10),
        Paragraph("Technical Summary (AI-generated)", styles["Heading2"]),
        Paragraph(inv.ai_technical_summary or "AI analysis unavailable for this run.", ai_style),
        Spacer(1, 10),
        Paragraph("Risk Assessment (rule-based)", styles["Heading2"]),
    ]

    risk_data = [
        ["Metric", "Score"],
        ["Confidence Score", inv.risk.confidence_score],
        ["Exposure Score", inv.risk.exposure_score],
        ["Investigation Completeness", inv.risk.investigation_completeness],
        ["Repository Exposure", inv.risk.repository_exposure],
        ["Technology Exposure", inv.risk.technology_exposure],
        ["Public Presence Score", inv.risk.public_presence_score],
    ]
    story.append(_styled_table(risk_data))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Collected Entities (raw facts)", styles["Heading2"]))
    entity_data = [["Type", "Value", "Source", "Confidence"]] + [
        [e.type.value, e.value[:60], e.source, f"{e.confidence:.2f}"] for e in inv.entities[:200]
    ]
    if len(entity_data) > 1:
        story.append(_styled_table(entity_data))
    else:
        story.append(Paragraph("No entities collected.", styles["BodyText"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("AI Recommendations (AI-generated)", styles["Heading2"]))
    if inv.ai_recommendations:
        for rec in inv.ai_recommendations:
            story.append(Paragraph(f"• {rec}", ai_style))
    else:
        story.append(Paragraph("No AI recommendations available.", styles["BodyText"]))
    story.append(Spacer(1, 12))

    if inv.warnings:
        story.append(Paragraph("Warnings / Limitations", styles["Heading2"]))
        for warning in inv.warnings:
            story.append(Paragraph(f"⚠ {warning}", warn_style))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "<i>Report generated by OSINT-X AI — collects only publicly available information from "
        "authorized/lawful sources. AI-generated sections are clearly marked and must be "
        "reviewed by a human analyst before action is taken.</i>",
        styles["BodyText"],
    ))

    doc.build(story)
    return output_path


def _styled_table(data: list[list]) -> Table:
    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return table
